### ISSUE TITLE
Try using Selenium timeout instead of arbitrary sleep for page waits

### ISSUE THREAD

**Issue by ssweens** [mikelor/FlyWhy#17]
Believe there is a Selenium timeout setting that you can set as an upper bound, but will otherwise proceed as soon as page load is complete and rendered.  Would speed things up when we start to process more than a handful at a time.

**Comment by mikelor** [comment]
Great suggestion. I did a quick search and it looks like selenium offers implicit & explicit waits
https://selenium-python.readthedocs.io/waits.html

As a quick test, I removed the "time.sleep" methods and no reviews were returned, although it ran much faster. :)
I like the idea of trying the selenium functions.
